name: Build and Push workflow
on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - ".github/**"
      - "configs/**"
  workflow_dispatch:
jobs:
  build-push:
    uses: Noves-Inc/devops/.github/workflows/build-push.yaml@master
    secrets:
      workflow_token: ${{ secrets.PAT }}
